### ISSUE TITLE
可否请教一下如何运行这个项目，希望可以得到回复。

### ISSUE THREAD

**Issue by aax1n** [ninedayhx/orb_slam2_ros_dense_map#1]

**Comment by Hezhexi2002** [comment]
我也想尝试复线这个项目，根据我的推测，按照一般ros项目的运行流程，应该是先在本地建立catkin_ws，然后在其中再建立src目录，将仓库源码clone到src目录下(注意需要递归clone)，然后cd到catkin_ws目录之后catkin_make，之后就可以启动相关的节点了

**Comment by ninedayhx** [comment]
你好，这个是基于官方给的包进行修改，增加稠密建图功能，你所描述的这些东西属于ros的基础知识，建议先学习一下ros的基本知识，把原版的代码跑通以后，再尝试自行修改，
原版代码网址如下
http://wiki.ros.org/orb_slam2_ros

**Comment by Hezhexi2002** [comment]
> 你好，这个是基于官方给的包进行修改，增加稠密建图功能，你所描述的这些东西属于ros的基础知识，建议先学习一下ros的基本知识，把原版的代码跑通以后，再尝试自行修改， 原版代码网址如下 http://wiki.ros.org/orb_slam2_ros

嗯嗯，谢谢大佬的亲自回复，这个orb_slam2_ros我之前在本地已经跑通了，但是原版里确实应该没有稠密建图的功能，我之前是跑了https://github.com/IATBOMSW/ORB-SLAM2_DENSE这个项目实现了稠密建图，意思大佬你项目中使用的orb_slam2_ros是修改过后增添了稠密点云输出的功能吗，我看仓库中orb_slam2_ros的链接并没有只想原版代码

**Comment by ninedayhx** [comment]
你好，谢谢你的关注，但我这个代码已经是2年前改的了，我刚重新clone下来看了一下代码，好像关键的代码部分被漏掉了，我看看原始代码再整合一下（我记得我上传的是原始代码，不知为何orb-slam2-ros这个包成为了空文件夹）

**Comment by Hezhexi2002** [comment]
> 你好，谢谢你的关注，但我这个代码已经是2年前改的了，我刚重新clone下来看了一下代码，好像关键的代码部分被漏掉了，我看看原始代码再整合一下（我记得我上传的是原始代码，不知为何orb-slam2-ros这个包成为了空文件夹）

哦哦，好的，麻烦大佬了，另外想问问大佬不会也是rmer吧，我看您fork了RoboRTS的repo，其实我现在想复现您这个项目就是为了Robomaster明年新赛季的哨兵，因为实验室目前只有一个astra pro相机，所以负责人让我用这个相机先试试效果，之前一直是跑的tum数据集，还没有尝试过自己录制的rosbag，而且orb_slam2_ros这个包我也不知道该怎么跑rosbag，如果大佬方便的话可以加个微信请教请教吗？😂

**Comment by ninedayhx** [comment]
orb-slam2如果要构建稠密图的话，实时性不够用在实际的比赛中，仅定位的话实时性还可以，真要实时性还得是激光slam,想要实时性较好的vslam的方案你可以看看港科大的vins或者是浙江大学高飞团队的，b站搜Fei_GAO，高飞团队的有完整的教程
rosbag就是你把传感器的数据按时间戳记录下来回放，你直接订阅它回放的topic就行
以上这些你都可以自行检索，我目前的方向已经改了，你可以自己学习一下，咨询我就没必要了，谢谢

**Comment by ninedayhx** [comment]
没有别的问题我就关掉这个issue了

**Comment by Hezhexi2002** [comment]
> orb-slam2如果要构建稠密图的话，实时性不够用在实际的比赛中，仅定位的话实时性还可以，真要实时性还得是激光slam,想要实时性较好的vslam的方案你可以看看港科大的vins或者是浙江大学高飞团队的，b站搜Fei_GAO，高飞团队的有完整的教程 rosbag就是你把传感器的数据按时间戳记录下来回放，你直接订阅它回放的topic就行 以上这些你都可以自行检索，我目前的方向已经改了，你可以自己学习一下，咨询我就没必要了，谢谢

好的，打扰大佬了，其实我们队里也有队员在用激光雷达做，不过不知道效果如何，还是谢谢大佬的建议了，不过最后还是想冒昧问一下大佬之前也参加过Robomaster吗？
